### ISSUE TITLE
I need help to fix it

### ISSUE THREAD

**Issue by inukaze** [cdemu/cdemu#1]
Hi there, i had do the follow : 

```
# Obtener la Arquitectura
Arquitectura=$(uname -m)
case "$Arquitectura" in
	x86)    Arquitectura="x32"						;;
	i?86)   Arquitectura="x32"						;;
	amd64)  Arquitectura="x64"						;;
	x86_64) Arquitectura="x64"						;;
	* ) echo    "Tu Arquitectura '$Arquitectura' -> NO ESTA SOPORTADA."	;;
esac

#Definir Variables :
PREFIJO="/usr"

#Crear directorios
mkdir -p /tmp/cdf 
mkdir -p "$PREFIJO"
cd /tmp/cdf

#Descargar (Requiere git preinstalado)
git clone https://github.com/cdemu/cdemu


# Establecer Optimizaciones
if [ "$Arquitectura" = "x64" ]; then
	export {C,CXX}FLAGS='-O2 -fPIC -march=native -mtune=native -pipe'
	export OPTFLAGS='-O2 -fPIC -march=native -mtune=native -pipe'
fi
if [ "$Arquitectura" = "x32" ]; then
	export {C,CXX}FLAGS='-O2 -march=native -mtune=native -pipe'
	export OPTFLAGS='-O2 -march=native -mtune=native -pipe'
fi

#Ingresar al directorio del codigo fuente

#Primero : El modulo para linux
cd cdemu/vhba-module ; make ; make install ; cd ..

#Segundo : La libreria para el sistema
cd libmirage ; mkdir build ; cd build ; cmake -DCMAKE_INSTALL_PREFIX:PATH="$PREFIJO" .. ; make ; make install ; cd ../../

#Tercero : El Demonio
cd cdemu-daemon ; mkdir build ; cd build ; cmake -DCMAKE_INSTALL_PREFIX:PATH="$PREFIJO" .. ; make ; make install ; cd ../../

#Cuarto : Analizador de Imagenes de disco
cd image-analyzer ; mkdir build ; cd build ; cmake -DCMAKE_INSTALL_PREFIX:PATH="$PREFIJO" .. ; make ; make install ; cd ../../

#Quinto : Cliente cdemu
cd cdemu-client/ ; mkdir build ; cd build ; cmake -DCMAKE_INSTALL_PREFIX:PATH="$PREFIJO" .. ; make ; make install ; cd ../../

#Sexto : Applet gcdemu [No me gustan que estas cosas esten hechas en python]
cd gcdemu/ ; mkdir build ; cd build ; cmake -DCMAKE_INSTALL_PREFIX:PATH="$PREFIJO" .. ; make ; make install ; cd ../../

ldconfig
```

Ok the thing is when i try to use cdemu or gcdemu appears this errors :+1: 

```
cdemu add-device
ERROR: Failed to connect to CDEmu daemon: g-dbus-error-quark: Error calling StartServiceByName for net.sf.cdemu.CDEmuDaemon: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process net.sf.cdemu.CDEmuDaemon exited with status 255 (25)
```

$ gcdemu

on Terminal :
```
AppIndicator tray icon mode
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(gcdemu:18782): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
```

on Desktop Envoronment appears a dialog error with the follow message : 

> Daemon autostart failed. Error: 
> g-dbus-error-quark: Error al llamar StartSrviceByName para net.sf.cdemu.CDEmuDaemon: 
> GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: 
> Process net.sfcdemu.CDEmuDaemon exited with status 255 (25)

I am using distro : Devuan ASCII [Basically Debian Stretch without systemd, because i use OpenRC, well if the user don't specify during the installation the default init be sysvinit]

**Comment by rokm** [comment]
The errors you are seeing come from the daemon auto-start attempts, and do not reveal the true cause of the error. Try manually running ```cdemu-daemon``` (as user!) to see what the error message is. 

My guess would be that ```/dev/vhba_ctl``` either does not exist or the user does not have proper read/write permissions on it.

If you are using debian-based system, I would recommend you to build the deb packages from sources and install those (admittedly I do not know if there are any incompatibilities with Devuan). To build deb from source, run ```dpkg-buildpackage -b -uc -tc``` from component's subdirectory. For example:
```
cd vhba-module
dpkg-buildpackage -b -uc -tc
``` 

If you prefer your manual installation method, you need to ensure that ```vhba``` module is inserted at system startup, and that your user has read/write permissions on ```/dev/vhba_ctl``` device. 

In our deb package, we achieve the former by creating ```/etc/modules-load.d/vhba.conf``` file with the following line:
```
vhba
```
Permissions are handled by the udev rule, which you can find in [vhba-module/debian/vhba-dkms.udev.](https://github.com/cdemu/cdemu/blob/master/vhba-module/debian/vhba-dkms.udev)

**Comment by inukaze** [comment]
Ok i will try with : 

```
echo 'KERNEL=="vhba_ctl", SUBSYSTEM=="misc", TAG+="uaccess"' | sudo tee /etc/udev/rules.d/vhba-dkms.udev
KERNEL=="vhba_ctl", SUBSYSTEM=="misc", TAG+="uaccess"
```
my user must be part of a certain group or something ?

**Comment by rokm** [comment]
No, if you use ```uaccess``` tag, there is no need for a special group.

But, you do need to make sure that the ```vhba``` module is loaded (```modprobe vhba```), otherwise ```/dev/vhba_ctl``` will not exist in the first place - which is the case in your example above.

**Comment by inukaze** [comment]
Just for you know if i use 
`dpkg-buildpackage -b -uc -tc`


with libmirage : 
```
[ 24%] Generating Mirage-3.2.gir
cd /media/Compartido/Liñux/cdf/git/cdemu/libmirage && /usr/bin/g-ir-scanner --add-include-path=/media/Compartido/Liñux/cdf/git/cdemu/libmirage --warn-all --namespace=Mirage --nsversion=3.2 -I/media/Compartido/Liñux/cdf/git/cdemu/libmirage -I/media/Compartido/Liñux/cdf/git/cdemu/libmirage/obj-x86_64-linux-gnu -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include --library=mirage --quiet --identifier-prefix=Mirage --symbol-prefix=mirage --include=GObject-2.0 --include=Gio-2.0 --include=GLib-2.0 --include=GModule-2.0 --no-libtool -L/media/Compartido/Liñux/cdf/git/cdemu/libmirage/obj-x86_64-linux-gnu --output=/media/Compartido/Liñux/cdf/git/cdemu/libmirage/obj-x86_64-linux-gnu/Mirage-3.2.gir mirage/mirage.c mirage/cdtext-coder.c mirage/compat-input-stream.c mirage/context.c mirage/contextual.c mirage/disc.c mirage/error.c mirage/file-stream.c mirage/filter-stream.c mirage/fragment.c mirage/index.c mirage/language.c mirage/object.c mirage/parser.c mirage/plugin.c mirage/sector.c mirage/session.c mirage/stream.c mirage/track.c mirage/utils.c mirage/version.c mirage/writer.c mirage/mirage.h mirage/cdtext-coder.h mirage/context.h mirage/contextual.h mirage/debug.h mirage/disc.h mirage/error.h mirage/file-stream.h mirage/filter-stream.h mirage/fragment.h mirage/index.h mirage/language.h mirage/object.h mirage/parser.h mirage/plugin.h mirage/sector.h mirage/session.h mirage/stream.h mirage/track.h mirage/types.h mirage/utils.h mirage/writer.h /media/Compartido/Liñux/cdf/git/cdemu/libmirage/obj-x86_64-linux-gnu/mirage/version.h
Traceback (most recent call last):
  File "/usr/bin/g-ir-scanner", line 66, in <module>
    sys.exit(scanner_main(sys.argv))
  File "/usr/lib/x86_64-linux-gnu/gobject-introspection/giscanner/scannermain.py", line 544, in scanner_main
    shlibs = create_binary(transformer, options, args)
  File "/usr/lib/x86_64-linux-gnu/gobject-introspection/giscanner/scannermain.py", line 421, in create_binary
    shlibs = resolve_shlibs(options, binary, options.libraries)
  File "/usr/lib/x86_64-linux-gnu/gobject-introspection/giscanner/shlibs.py", line 146, in resolve_shlibs
    _resolve_non_libtool(options, binary, non_libtool))
  File "/usr/lib/x86_64-linux-gnu/gobject-introspection/giscanner/shlibs.py", line 119, in _resolve_non_libtool
    line = line.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 40: ordinal not in range(128)
CMakeFiles/mirage-typelib.dir/build.make:65: fallo en las instrucciones para el objetivo 'Mirage-3.2.gir'
make[3]: *** [Mirage-3.2.gir] Error 1
make[3]: se sale del directorio '/media/Compartido/Liñux/cdf/git/cdemu/libmirage/obj-x86_64-linux-gnu'
CMakeFiles/Makefile2:181: fallo en las instrucciones para el objetivo 'CMakeFiles/mirage-typelib.dir/all'
make[2]: *** [CMakeFiles/mirage-typelib.dir/all] Error 2
make[2]: se sale del directorio '/media/Compartido/Liñux/cdf/git/cdemu/libmirage/obj-x86_64-linux-gnu'
Makefile:130: fallo en las instrucciones para el objetivo 'all'
make[1]: *** [all] Error 2
make[1]: se sale del directorio '/media/Compartido/Liñux/cdf/git/cdemu/libmirage/obj-x86_64-linux-gnu'
dh_auto_build: make -j1 returned exit code 2
debian/rules:21: fallo en las instrucciones para el objetivo 'binary'
make: *** [binary] Error 2
dpkg-buildpackage: fallo: fakeroot debian/rules binary devolvió un estado de salida de error 2
```

i supose that "ascii" is the codename of distro and this process was waiting "stretch"

**Comment by rokm** [comment]
> Just for you know if i use
> `dpkg-buildpackage -b -uc -tc`
> 
> with libmirage :
> 
> ```
> [ 24%] Generating Mirage-3.2.gir
> cd /media/Compartido/Liñux/cdf/git/cdemu/libmirage && /usr/bin/g-ir-scanner --add-include-path=/media/Compartido/Liñux/cdf/git/cdemu/libmirage --warn-all --namespace=Mirage --nsversion=3.2 -I/media/Compartido/Liñux/cdf/git/cdemu/libmirage -I/media/Compartido/Liñux/cdf/git/cdemu/libmirage/obj-x86_64-linux-gnu -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include --library=mirage --quiet --identifier-prefix=Mirage --symbol-prefix=mirage --include=GObject-2.0 --include=Gio-2.0 --include=GLib-2.0 --include=GModule-2.0 --no-libtool -L/media/Compartido/Liñux/cdf/git/cdemu/libmirage/obj-x86_64-linux-gnu --output=/media/Compartido/Liñux/cdf/git/cdemu/libmirage/obj-x86_64-linux-gnu/Mirage-3.2.gir mirage/mirage.c mirage/cdtext-coder.c mirage/compat-input-stream.c mirage/context.c mirage/contextual.c mirage/disc.c mirage/error.c mirage/file-stream.c mirage/filter-stream.c mirage/fragment.c mirage/index.c mirage/language.c mirage/object.c mirage/parser.c mirage/plugin.c mirage/sector.c mirage/session.c mirage/stream.c mirage/track.c mirage/utils.c mirage/version.c mirage/writer.c mirage/mirage.h mirage/cdtext-coder.h mirage/context.h mirage/contextual.h mirage/debug.h mirage/disc.h mirage/error.h mirage/file-stream.h mirage/filter-stream.h mirage/fragment.h mirage/index.h mirage/language.h mirage/object.h mirage/parser.h mirage/plugin.h mirage/sector.h mirage/session.h mirage/stream.h mirage/track.h mirage/types.h mirage/utils.h mirage/writer.h /media/Compartido/Liñux/cdf/git/cdemu/libmirage/obj-x86_64-linux-gnu/mirage/version.h
> Traceback (most recent call last):
>   File "/usr/bin/g-ir-scanner", line 66, in <module>
>     sys.exit(scanner_main(sys.argv))
>   File "/usr/lib/x86_64-linux-gnu/gobject-introspection/giscanner/scannermain.py", line 544, in scanner_main
>     shlibs = create_binary(transformer, options, args)
>   File "/usr/lib/x86_64-linux-gnu/gobject-introspection/giscanner/scannermain.py", line 421, in create_binary
>     shlibs = resolve_shlibs(options, binary, options.libraries)
>   File "/usr/lib/x86_64-linux-gnu/gobject-introspection/giscanner/shlibs.py", line 146, in resolve_shlibs
>     _resolve_non_libtool(options, binary, non_libtool))
>   File "/usr/lib/x86_64-linux-gnu/gobject-introspection/giscanner/shlibs.py", line 119, in _resolve_non_libtool
>     line = line.decode('ascii')
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 40: ordinal not in range(128)
> CMakeFiles/mirage-typelib.dir/build.make:65: fallo en las instrucciones para el objetivo 'Mirage-3.2.gir'
> make[3]: *** [Mirage-3.2.gir] Error 1
> make[3]: se sale del directorio '/media/Compartido/Liñux/cdf/git/cdemu/libmirage/obj-x86_64-linux-gnu'
> CMakeFiles/Makefile2:181: fallo en las instrucciones para el objetivo 'CMakeFiles/mirage-typelib.dir/all'
> make[2]: *** [CMakeFiles/mirage-typelib.dir/all] Error 2
> make[2]: se sale del directorio '/media/Compartido/Liñux/cdf/git/cdemu/libmirage/obj-x86_64-linux-gnu'
> Makefile:130: fallo en las instrucciones para el objetivo 'all'
> make[1]: *** [all] Error 2
> make[1]: se sale del directorio '/media/Compartido/Liñux/cdf/git/cdemu/libmirage/obj-x86_64-linux-gnu'
> dh_auto_build: make -j1 returned exit code 2
> debian/rules:21: fallo en las instrucciones para el objetivo 'binary'
> make: *** [binary] Error 2
> dpkg-buildpackage: fallo: fakeroot debian/rules binary devolvió un estado de salida de error 2
> ```
> 
> i supose that "ascii" is the codename of distro and this process was waiting "stretch"

I think the issue is that you have a non-ASCII character in the path to source (the 'ñ' in "/media/Compartido/Liñux/cdf/git/cdemu/libmirage/").

It is likely an issue with gobject-introspection that has probably been fixed in the later versions, because I cannot reproduce it on Fedora 30.

> ```
> $ sudo modprobe vhba
> modprobe: FATAL: Module vhba not found in directory /lib/modules/4.9.0-9-amd64
> ```

If you install the module from source using ```make install```, I think you need to manually run a ```depmod -a``` as well in order for module to become visible. Not sure why, though.


> ```
> dpkg-buildpackage -b -uc -tc
> sudo dpkg -i vhba-dkms_20190302-1_all.deb
> Seleccionando el paquete vhba-dkms previamente no seleccionado.
> (Leyendo la base de datos ... 589942 ficheros o directorios instalados actualmente.)
> Preparando para desempaquetar vhba-dkms_20190302-1_all.deb ...
> Desempaquetando vhba-dkms (20190302-1) ...
> Configurando vhba-dkms (20190302-1) ...
> Loading new vhba-20190302 DKMS files...
> Building for 4.9.0-9-amd64
> Building initial module for 4.9.0-9-amd64
> Done.
> 
> vhba:
> Running module version sanity check.
> 
> Good news! Module version 20190302 for vhba.ko
> exactly matches what is already found in kernel 4.9.0-9-amd64.
> DKMS will not replace this module.
> You may override by specifying --force.
> 
> depmod............................
> 
> DKMS: install completed.
> WARNING: Configuration already exists.
> 
> [ inukaze | 09-06-2019 | 05:54  ]
> [cdemu]$ sudo modprobe vhba
> [sudo] password for inukaze: 
> 
> [ inukaze | 09-06-2019 | 05:54  ]
> [cdemu]$ sudo udevadm control --reload-rules ; sudo udevadm trigger
> 
> $ cdemu-daemon
> Starting CDEmu daemon with following parameters:
>  - num devices: 1
>  - control device: /dev/vhba_ctl
>  - audio driver: null
>  - bus type: session
> 
> cdemu0: Kernel I/O: failed to open control device /dev/vhba_ctl: Permiso denegado!
> cdemu: Daemon: failed to start device #0!
> cdemu: Daemon: failed to create device!
> Daemon initialization and start failed!

The issue is that your user does not have read-write permissions on /dev/vhba_ctl. The ```uaccess``` tag may be systemd-specific, so it does not work for you. Maybe you can try using ```udev-acl``` tag, which we were using on earlier Ubuntu versions:
```
KERNEL=="vhba_ctl", SUBSYSTEM=="misc", TAG+="udev-acl"
```
Or, you can modify the udev rule to apply permissions to group and then add your user to that group:
```
KERNEL=="vhba_ctl", MODE="0660", OWNER="root", GROUP="cdrom"
```

> $ sudo cdemu-daemon &
> Starting CDEmu daemon with following parameters:
>  - num devices: 1
>  - control device: /dev/vhba_ctl
>  - audio driver: null
>  - bus type: session

While running the daemon with root privileges does work around the permissions issue, it ultimately results in errors in clients that are run as normal user. This is because user-started clients connect to a different D-Bus session that root-started daemon. And because the clients effectively do not see a daemon instance, they try to auto-start another one, resulting in the same errors as you observed earlier.

**Comment by inukaze** [comment]
Thanks i do : 

```
echo 'KERNEL=="vhba_ctl", SUBSYSTEM=="misc", TAG+="udev-acl"' | sudo tee /etc/udev/rules.d/vhba-dkms.udev ; sudo udevadm control --reload-rules ; sudo udevadm trigger ; cdemu-daemon &
gcdemu
```

and now its working
