### ISSUE TITLE
GCDEmu taskbar icon does not appear on Fedora 35 KDE

### ISSUE THREAD

**Issue by r2rX** [cdemu/cdemu#21]
Hello there,

I recently installed CDemu + GCDEmu from your Fedora COPR (https://copr.fedorainfracloud.org/coprs/rok/cdemu/). All packages installed fine, the kernel module also initialized successfully and 'cdemu status' indicated that the daemon is running. The only issue is when opening GCDEmu. The process seems to start (as seen in system activity) but the icon does not appear in the KDE Plasma desktop tray.

**Comment by rokm** [comment]
If you run `gcdemu` from terminal, does the output contain an `AppIndicator tray icon mode` or a `Gtk tray icon mode`? If the latter, try installing `libappindicator-gtk3` (or `libindicator`) to use the AppIndicator instead of deprecated GtkTrayIcon.

**Comment by r2rX** [comment]
@rokm , you were on the mark. It was attempting to open in Gtk tray icon mode. After installing libappindicator-gtk3, it loads fine now. Thanks a bunch!

If I make a suggestion, to make it easier for (future) Fedora users, the instructions on the COPR should include installing libappindicator-gtk3 and kernel-devel (for the users currently used kernel version) as that was necessary in order to initialize the daemon (of which the devel package isn't installed by default). I'm not sure if adding them as dependencies is something you'd want to do for your package but, if not, at least to point those two out.

Thanks for the help!
