### ISSUE TITLE
[Feature Request] Support redump-style multisession images.

### ISSUE THREAD

**Issue by HeroponRikiBestest** [cdemu/cdemu#31]
I understand that it wouldn't be a priority, but it would be nice if cdemu supported redump-style multisession images, since at the moment, they usually need to be converted via isobuster or another tool before a virtual drive will accept them. Currently, mounting one will handle most of the audio tracks fine, but the last audio track in session 1 will be broken and not function; the data track on session 2 will attempt to be mounted, but will give the error `Error mounting /dev/sr0 at /media/[username]/[volume name]: wrong fs type, bad option, bad superblock on /dev/sr0, missing codepage or helper program, or other error`. Attached is an example of a cuefile for said format.
[example.zip](https://github.com/cdemu/cdemu/files/14212823/example.zip)

Additionally, the redump website strips a few lines from the end of the cuefile when hosting the cues:

```
REM LEAD-OUT 01:30:00

REM LEAD-IN 01:00:00
REM PREGAP 00:02:00
```
as can be seen in this additional example:
[example2.zip](https://github.com/cdemu/cdemu/files/14212860/example2.zip)

As far as I understand, these lines should consistently be the same, and could be assumed to be there if not. However, if the cdemu developers decide that they don't want to add compensation for redump.org unnecessarily removing some lines, that's perfectly understandable. Additionally, I understand not wanting to spend time adding the format in general, even if it would be nice, hence labeling it a feature request. 

If any other information needs to be provided, whether here or on another platform, please let me know, and I will happily do so

**Comment by nvllsvm** [comment]
I'm able to work around this by converting the cue to separate `.toc` files using https://github.com/nvllsvm/dotfiles/blob/master/scripts/commands/redumper/redumper-cue-to-toc . I've uploaded an example redumper dump - including the original cue and logs - to https://archive.org/details/duke_nukem_music_to_score_by .

**Output of `cd-info <dev>`**
- [Physical Disc](https://github.com/user-attachments/files/16116815/cdinfo_physical_disc.txt)
- [cdemu (redumper cue)](https://github.com/user-attachments/files/16116814/cdinfo_cdemu_redumper_cue.txt)
- [cdemu (multiple toc derived from the redumper cue)](https://github.com/user-attachments/files/16116813/cdinfo_cdemu_multi_toc.txt)

Using the redumper cue, cdemu does not emulate the expected disc layout:
```
$ diff cdinfo_physical_disc.txt cdinfo_cdemu_redumper_cue.txt
10,12c10,12
< Vendor                      : PLEXTOR 
< Model                       : DVDR   PX-760A  
< Revision                    : 1.07
---
> Vendor                      : CDEmu   
> Model                       : CD-ROM          
> Revision                    : 1.0 
21c21
< Can hard reset device                     : Yes
---
> Can hard reset device                     : No
39c39
<   Can write DVD-RAM                       : No
---
>   Can write DVD-RAM                       : Yes
59,60c59,60
<  13: 48:47:42  219417 data   false  no   
< 170: 68:09:30  306555 leadout (687 MB raw, 687 MB formatted)
---
>  13: 44:27:49  199924 data   false  no   
> 170: 63:49:37  287062 leadout (643 MB raw, 643 MB formatted)
62c62
< Last CD Session LSN: 219417
---
> Last CD Session LSN: 199924
72c72
< session #2 starts at track 13, LSN: 219417, ISO 9660 blocks: 306403
---
> session #2 starts at track 13, LSN: 199924, ISO 9660 blocks: 306403
```

The second session's data track is unusable (see this for a good explanation of why https://www.bitsgalore.org/2017/04/25/imaging-cd-extra-blue-book-discs)
```
$ sudo mount /dev/sr0 /mnt/tmp1
mount: /mnt/tmp1: wrong fs type, bad option, bad superblock on /dev/sr0, missing codepage or helper program, or other error.
       dmesg(1) may have more information after failed mount system call.
```

Using the derived toc files, the disc layout is as expected:
```
$ diff cdinfo_physical_disc.txt cdinfo_cdemu_multi_toc.txt
10,12c10,12
< Vendor                      : PLEXTOR 
< Model                       : DVDR   PX-760A  
< Revision                    : 1.07
---
> Vendor                      : CDEmu   
> Model                       : CD-ROM          
> Revision                    : 1.0 
21c21
< Can hard reset device                     : Yes
---
> Can hard reset device                     : No
39c39
<   Can write DVD-RAM                       : No
---
>   Can write DVD-RAM                       : Yes
```

I'm also able to mount the second session's data track:
```
# mount /dev/sr0 /mnt/tmp1
mount: /mnt/tmp1: WARNING: source write-protected, mounted read-only.
# ls /mnt/tmp1
CALLS  CDPLUS  DESKTOPS  DUKE1  DUKE3D  GUIDE  ISMS  PICTURES  QT302  SAVERS  XTRAS  AUTORUN.INF  BELIB.CST  DUKE.EXE  INTRO.DIR  INTRO.MOV  LINGO.INI  MAIN.DIR  MSVCRT.EXE  README.TXT  SLIDESHOW.DIR
```

**Comment by nvllsvm** [comment]
Actually, this seems to be a bug in libmirage where the previous session's last track is never finished. This should fix it:

```
diff --git a/images/image-cue/parser.c b/images/image-cue/parser.c
index 9ec5ff91..8aaa0d80 100644
--- a/images/image-cue/parser.c
+++ b/images/image-cue/parser.c
@@ -468,6 +468,12 @@ static void mirage_parser_cue_add_session (MirageParserCue *self, gint number)
        which isn't indicated because only index 01 is used) */
     self->priv->leadout_correction = leadout_length + 150;
 
+    GError *local_error = NULL;
+    if (!mirage_parser_cue_finish_last_track(self, &local_error)) {
+        MIRAGE_DEBUG(self, MIRAGE_DEBUG_WARNING, "%s: failed to finish last track for session previous to #%i: %s\n!", __debug__, number, local_error->message);
+        g_error_free(local_error);
+    }
+
     /* Add new session, store the pointer but release the reference */
     self->priv->cur_session = g_object_new(MIRAGE_TYPE_SESSION, NULL);
     mirage_disc_add_session_by_index(self->priv->disc, -1, self->priv->cur_session);
```

**Comment by HeroponRikiBestest** [comment]
Tested it out, seems to work great, both with directly-dumped bin/cue files, and also with the redump.org-generated cuefiles. Maybe worth noting, there is a discrepancy between having the physical disc mounted and the disc mounted in cdemu, but it's a case where I don't know if it's actually an issue, because it doesn't work properly in either case. On Linux mint 21.2 (and all previous versions) for cdplus discs where there's a `cdplus` directory and a `pictures` directory, if I attempt to copy the `pictures` directory from the physical disc, all the files copy over; wheras, from the disc mounted in cdemu, it hits an error when trying to copy the jacket01.00n, jacket01.00s, and jacket01.00t files from the mounted image. I say this might not actually be an issue because they aren't copied from the physical disc properly, either- they appear to be stripped in the beginning and end, having the first 68 bytes removed and the last ~300 (varies) bytes removed. If I pass cdemu through to a VM (in this case, running windows xp) and copy this folder, the files copy properly. Ultimately, it seems that whatever mint's default file manager is doing here is wrong, so there's probably no real issue with cdemu here, but I figured it was maybe worth noting that there was a discrepancy in how they're returning erroneously.


In case anyone is wondering, even though it doesn't appear to affect this at all: redump.org-generated cuefiles are  unfortunately are stripped a little, having
`REM LEAD-OUT 01:30:00
REM SESSION 02
REM LEAD-IN 01:00:00
REM PREGAP 00:02:00`
turned into 
`REM SESSION 02`
in the cuesheet. This doesn't seem to affect anything with cdemu, thankfully?

**Comment by rokm** [comment]
> *In case anyone is wondering, even though it doesn't appear to affect this at all: redump.org-generated cuefiles are unfortunately are stripped a little from the original dumps (we can't do anything about this at the moment, even though this ideally should not be done), having
> 
> ```
> REM LEAD-OUT 01:30:00
> REM SESSION 02
> REM LEAD-IN 01:00:00
> REM PREGAP 00:02:00
> ```
> 
> turned into `REM SESSION 02` in the cuesheet. This doesn't seem to affect anything with cdemu, thankfully, and both types of cues appear to work properly.

I suppose those are standard lead-out and lead-in lengths; libmirage's CUE parser has the same values hardcoded when opening new session:

https://github.com/cdemu/cdemu/blob/b1ed04e972f77c615a76b41dc0e7a6cb163be819/libmirage/images/image-cue/parser.c#L455-L456

6750 sectors = 90 seconds = 01:30:00
4500 sectors = 60 seconds = 01:00:00

(And if I recall correctly, 2-second pregap is also added automatically for the first track in new session).

So it works out for standard multi-session layouts.
