### ISSUE TITLE
Can't add new device (gcdemu) OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by ukbeast** [cdemu/cdemu#4]
```
 gcdemu 
AppIndicator tray icon mode
Traceback (most recent call last):
  File "/usr/bin/gcdemu", line 1949, in on_connection_established
    self.add_device(i)
  File "/usr/bin/gcdemu", line 1995, in add_device
    device = self.create_device(self.cdemu, num)
  File "/usr/bin/gcdemu", line 2099, in create_device
    return gCDEmuDevice_Indicator(cdemu, d)
  File "/usr/bin/gcdemu", line 1737, in __init__
    gCDEmuDevice.__init__(self, cdemu, d)
  File "/usr/bin/gcdemu", line 1490, in __init__
    self.file_chooser = gCDEMuFileChooserDialog(cdemu.supported_parsers, cdemu.supported_filter_streams)
  File "/usr/bin/gcdemu", line 1005, in __init__
    self.add_buttons(_("Cancel"), Gtk.ResponseType.CANCEL, _("Open"), Gtk.ResponseType.ACCEPT)
AttributeError: 'gCDEMuFileChooserDialog' object has no attribute 'add_buttons'
```

Here is my .spec https://build.opensuse.org/package/view_file/home:ukbeast89:branches:X11:Utilities/gcdemu/gcdemu.spec
You can also read my buildlog here https://build.opensuse.org/package/live_build_log/home:ukbeast89:branches:X11:Utilities/gcdemu/openSUSE_Tumbleweed/x86_64

**Comment by rokm** [comment]
I cannot seem to reproduce this with a Tumbleweed VM (fresh installation using `openSUSE-Tumbleweed-DVD-x86_64-Snapshot20200429-Media.iso`). 

Both `gcdemu-3.2.1-1.1` (from main repository), your `gcdemu-3.2.4-15.1` build (manual upgrade), and git master version seem to work correctly, in spite of a Gdk-related error message:
```
rok@localhost:~> gcdemu 
AppIndicator tray icon mode

(gcdemu:16618): Gdk-CRITICAL **: 18:38:08.811: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
```

**Comment by ukbeast** [comment]
Are you using plasma DE?
I'm thinking it maybe related to a missing lib on my end.

**Comment by ukbeast** [comment]
I've managed to solve issue 
python3-gobject-Gdk lib was needed.
