### ISSUE TITLE
Update / remove source tarballs information in cdemu download page

### ISSUE THREAD

**Issue by crvigh** [cdemu/cdemu#6]
https://cdemu.sourceforge.io/project/#download

### Source tarballs

**Official tarballs:**
Here is the official source tarballs for our latest release.

**Core software:**
vhba-module [20190831]
cdemu-daemon [3.2.3]
libmirage [3.2.3]

**Client applications:**
gCDEmu [3.2.3]
cdemu-client [3.2.3]

**Image analyzer:**
image-analyzer [3.2.3]

The above information is old and the links point to a different version. Update the page or remove them, as the link to sourceforge download page ( https://sourceforge.net/projects/cdemu/files/ ) should suffice.

**Comment by hstokset** [comment]
Sorry for late reply. Links have been updated.
