### ISSUE TITLE
Settlers 2 CDDA tracks crash cdemu-daemon at the end of the track

### ISSUE THREAD

**Issue by stefand** [cdemu/cdemu#8]
I am using dosemu2 to play Settlers 2. The game's CD contains audio tracks. When Audio playback is turned on in the game, dosemu2 will forward the request to cdemu and cdemu plays one track fine.

At the end of one track cdemu-daemon dies with a failed assertion due to a CDEMU_DEBUG(DAEMON_DEBUG_ERROR) line. The attached diff fixes the assert. I tried to debug the underlying cause a little, and it seems libmirage's mirage_sector_get_data returns a len of -1, which is obviously rejected by ao_play.

The attached patch downgrades the error to a warning, fixing the crash and making the game proceed to the next track. Interestingly, it also skips to the next track now if some other process accesses the drive (e.g. I mount it, dd if=/dev/sr1 of=/dev/null or something like it). I haven't yet tried with a different CDDA player (I have to find one) to see if a dosemu2 problem is involved too. Either way I think cdemu-daemon shouldn't just dump core and potentially leave a mounted drive dangling.

[cdemu.txt](https://github.com/cdemu/cdemu/files/6217146/cdemu.txt)

**Comment by rokm** [comment]
Thanks for the report. You are correct - `DAEMON_DEBUG_ERROR` calls `abort()` and therefore `DAEMON_DEBUG_WARNING` should be used instead. 

There was additional instance where `DAEMON_DEBUG_ERROR` was used, and I've replaced them both in 216dac2.

**Comment by stefand** [comment]
The fix works as advertised. I am closing this; if you want to investigate why libmirage returns a length of -1 I can provide you with the CD image.

**Comment by rokm** [comment]
> If you want to investigate why libmirage returns a length of -1 I can provide you with the CD image.

That'd be great, thanks. 

I was trying to reproduce the crash during playback with the couple of mixed-track images that I have at hand, but no success...

**Comment by stefand** [comment]
I think the game executable is somehow involved in this bug.

I have 3 CD images with Audio tracks, all from games: Settlers 2, Screamer 2 and Worms 2. If I feed the Worms 2 image to Settlers 2 the error is triggered (and with your fix reverted) cdemu-daemon crashes. Same if I feed the Screamer 2 CD to Settlers.

However, feeding the Settlers image to Worms 2 running via Wine does not cause the problem. I am not 100% sure if Worms 2 tells the CD drive to send audio data to the sound card because the playback stops instantly as soon as I send Worms 2 a SIGSTOP though.

I found a DOS cd player here: http://www.fysnet.net/cdp.htm. Running it in dosemu2 correctly plays the settlers 2 audio tracks without crashing a (pre-fix) cdemu. And just like settlers 2 it keeps playing the CD after quitting, and cdemu continues playing if I SIGKILL dosemu2 - so it does use cdemu's audio decoding code path.

Another factoid: As previously stated, if I access the CD in any other way while S2 is playing it, cdemu crashes. If I quit S2 and let the music continue to play and then access the CD, cdemu stops playing the audio track, but doesn't crash.

The original problem - cdemu crashes on track end in Settlers 2 - occurs regardless of if the CD is mounted on the Linux side. For file access dosemu2 uses the Linux file APIs.

**Comment by rokm** [comment]
> However, feeding the Settlers image to Worms 2 running via Wine does not cause the problem. I am not 100% sure if Worms 2 tells the CD drive to send audio data to the sound card because the playback stops instantly as soon as I send Worms 2 a SIGSTOP though.

I think wine's implementation of `mcicda` driver explicitly avoids using `PLAY AUDIO` command set, and instead plays the data it reads via `READ CD` command. So if Worms 2 does its playback via `mcicda`, cdemu's audio playback emulation is not used.

> Another factoid: As previously stated, if I access the CD in any other way while S2 is playing it, cdemu crashes.

Does it also happen if you use `cdp` to play audio and access the CD in any other way?

**Comment by stefand** [comment]
> I think wine's implementation of mcicda driver explicitly avoids using PLAY AUDIO command set

Indeed. I saw it has a PLAY AUDIO codepath too, I'll play with it out of curiosity.

MacOS removed classic audio playback years ago (afaik it was never available for Intel apps and emulated for PPC ones in Rosetta 1).

> > Another factoid: As previously stated, if I access the CD in any other way while S2 is playing it, cdemu crashes.
> 
> Does it also happen if you use `cdp` to play audio and access the CD in any other way?

No. In this case playback stops but the DAEMON_DEBUG_ERROR path is not triggered. I am not sure if it means much though. I can't reproduce the crash-on-mount issue any more even with S2 running, even though I didn't knowingly make any changes. The crash-on-track-end is reliable though.

**Comment by stefand** [comment]
Another factoid to support the race condition theory: If I stop dosemu2 (via SIGSTOP) with the game running before the track ends cdemu does not crash. When I resume it afterwards the game proceeds successfully to the next track.

**Comment by stefand** [comment]
It looks like on a track change the new thread starts before the old one tears down the audio device. The libao access code isn't protected by the device mutex, but the ao device is shared.

```
cdemu0: AudioPlay: playing sector 312726 (0x4C596)
cdemu0: AudioPlay: failed to get sector 0x4C596: Session address 312726 (0x4C596) out of range!
cdemu0: AudioPlay: playback thread end
cdemu0: AudioPlay: closing audio device
cdemu0: AudioPlay: starting playback (0x2E1DC->0x30E9C)...
[New Thread 0x7fffdf7fe640 (LWP 484742)]
cdemu0: AudioPlay: opening audio device
ao_alsa WARNING: Unable to open surround playback.  Trying default device...
[New Thread 0x7fffdeffd640 (LWP 484743)]
cdemu0: AudioPlay: playback thread start
cdemu0: AudioPlay: playing sector 188892 (0x2E1DC)
cdemu0: AudioPlay: mirage says len 2352!
cdemu0: AudioPlay: playing sector 188893 (0x2E1DD)
cdemu0: AudioPlay: mirage says len 2352!
cdemu0: AudioPlay: playing sector 188894 (0x2E1DE)
cdemu0: AudioPlay: mirage says len 2352!
[Thread 0x7fffdffff640 (LWP 484160) exited]
[Thread 0x7ffff4991640 (LWP 484159) exited]
cdemu0: AudioPlay: playing sector 188895 (0x2E1DF)
cdemu0: AudioPlay: mirage says len 2352!
cdemu0: AudioPlay: playback error, len 2352!
```
/

**Comment by stefand** [comment]
And finally here is a crude fix. It is really ugly though, with its asymmetric mutex locking / unlocking in that loop.

My first attempt was to always hold the mutex except around mirage_sector_get_data and ao_play/g_usleep, but that doesn't work because the main thread (where start/stop comes from) holds the mutex before setting self->priv->status and then waits for the thread to exit in case of pause/stop. In case of pause/stop the race is not a problem because the main thread waits for the playback thread to exit before giving the application another chance to start playback.

Now the log looks much nicer and the game proceeds to the next track without triggering the ao playback error:

```
cdemu0: AudioPlay: playback thread reached the end
cdemu0: AudioPlay: playback thread end
cdemu0: AudioPlay: closing audio device
[Thread 0x7fffdffff640 (LWP 492137) exited]
[Thread 0x7ffff4991640 (LWP 492136) exited]
cdemu0: AudioPlay: starting playback (0x37714->0x3A90E)...
[New Thread 0x7fffdffff640 (LWP 492682)]
cdemu0: AudioPlay: opening audio device
ao_alsa WARNING: Unable to open surround playback.  Trying default device...
[New Thread 0x7fffdf7fe640 (LWP 492683)]
cdemu0: AudioPlay: playback thread start

```

I'll leave the cleanup up to you.

[play-fix.txt](https://github.com/cdemu/cdemu/files/6222684/play-fix.txt)

**Comment by rokm** [comment]
Great, thanks!

> My first attempt was to always hold the mutex except around mirage_sector_get_data and ao_play/g_usleep, but that doesn't work because the main thread (where start/stop comes from) holds the mutex before setting self->priv->status and then waits for the thread to exit in case of pause/stop.

Aha, that explains why mutex locking wasn't pushed all the way up, above the first if block in the while loop.

So the problem here was that as soon as we signaled AUDIO_STATUS_COMPLETED, S2 was trying to restart the playback, resulting in the race. I suspect the same could happen when we signal AUDIO_STATUS_ERROR (maybe not with S2, depending on how it is coded). So expanding on your patch, we should probably be setting `self_shutdown` instead of unlocking the mutex in lines 92 and 103 as well.

**Comment by rokm** [comment]
Also, could you please open a PR with the patch, so you get properly credited for the fix in the commit history?

**Comment by stefand** [comment]
Actually, I am contemplating if it isn't better to reap the playback thread in cdemu_audio_start_playing if self->priv->playback_thread != and maybe in cdemu_audio_get_status too. Otherwise a pile of zombie threads will accumulate if stop() is never called.

The attached fix works too, but I guess it depends on Settlers 2 polling the sense status. (How else would it learn when a track is finished?)

[play-fix2.txt](https://github.com/cdemu/cdemu/files/6222923/play-fix2.txt)
